### ISSUE TITLE
anyone facing this issue , connection not reaching the destination 

### ISSUE THREAD

**Issue by anoircp** [sprov065/v2-ui#311]
hi 

it is the first time i tried install v2ray , i have tried on two servers from different providers , same issue here

try as well to connect from my computer or windows rdp , same 

v2ray client : 

The ping of current service: -1ms
 tcp:127.0.0.1:61925 accepted tcp:www.google.com:443 [proxy] 
 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [dial tcp xx.xx.xx.xx:37773: connectex: No connection could be made because the target machine actively refused it.] > v2ray.com/core/common/retry: all retry attempts failed

note: firewall already disabled!

===============

v2-ui log

25:38-root-WARNING-v2ray api code 255
26:11-root-WARNING-v2ray api code 255
26:45-root-WARNING-v2ray api code 255
27:18-root-WARNING-v2ray api code 255
27:51-root-WARNING-v2ray api code 255

=================

● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-08-19 05:54:50 CEST; 40min ago
 Main PID: 24570 (v2ray)
    Tasks: 6 (limit: 2301)
   CGroup: /system.slice/v2ray.service
           └─24570 /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json

Aug 19 05:54:50 ubuntu-2gb-nbg1-2 systemd[1]: Stopped V2Ray Service.
Aug 19 05:54:50 ubuntu-2gb-nbg1-2 systemd[1]: Started V2Ray Service.
Aug 19 05:54:50 ubuntu-2gb-nbg1-2 v2ray[24570]: V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 linux/amd64)
Aug 19 05:54:50 ubuntu-2gb-nbg1-2 v2ray[24570]: A unified platform for anti-censorship.
Aug 19 05:54:50 ubuntu-2gb-nbg1-2 v2ray[24570]: 2020/08/19 05:54:50 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
Aug 19 05:54:50 ubuntu-2gb-nbg1-2 v2ray[24570]: v2ctl> Read config:  /usr/local/etc/v2ray/config.json
Aug 19 05:54:50 ubuntu-2gb-nbg1-2 v2ray[24570]: 2020/08/19 05:54:50 [Warning] v2ray.com/core: V2Ray 4.27.0 started

===============
 v2-ui.service - v2-ui Service
   Loaded: loaded (/etc/systemd/system/v2-ui.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-08-19 02:10:22 CEST; 4h 28min ago
 Main PID: 30864 (v2-ui)
    Tasks: 3 (limit: 2301)
   CGroup: /system.slice/v2-ui.service
           ├─30864 /usr/local/v2-ui/v2-ui
           └─30865 /usr/local/v2-ui/v2-ui

Aug 19 02:10:22 ubuntu-2gb-nbg1-2 systemd[1]: Started v2-ui Service.

==============
v2ray -config value
V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 linux/amd64)
A unified platform for anti-censorship.
main: failed to read config files: [value] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: 
v2ctl> Read config:  value
panic: open value: no such file or directory

goroutine 1 [running]:
v2ray.com/core/common.Must(...)
	v2ray.com/core/common/common.go:17
v2ray.com/core/infra/control.(*ConfigCommand).Execute(0xfcce30, 0xc0000301a0, 0x1, 0x1, 0xc00018e9a8, 0x9c211c520d770801)
	v2ray.com/core/infra/control/config.go:42 +0x673
main.main()
	v2ray.com/core/infra/control/main/main.go:35 +0x217 > exit status 2

i think there is a bad connection between v2-ui config and v2ray regarding the last 3 days v2ray and previous updates!
everything is on default values , got errors after the fresh installation 
any idea!

**Comment by anoircp** [comment]
in the v2ray status 

Aug 19 05:54:50 ubuntu-2gb-nbg1-2 v2ray[24570]: v2ctl> Read config: /usr/local/etc/v2ray/config.json

i seem that v2ray reading the default config , and not the panel config , 
putting a simple config in /usr/local/etc/v2ray/config.json

now hiting a little response to the tests , ex download speed , tcp ping , service status



v2ctl> Read config:  stdin:
2020/08/19 06:02:35 [Warning] v2ray.com/core: V2Ray 4.27.0 started
2020/08/19 06:02:36 127.0.0.1:62520 accepted http://speedtest-sgp1.digitalocean.com/10mb.test [proxy10911] 
2020/08/19 06:02:44 [Warning] [1561172116] v2ray.com/core/app/proxyman/inbound: connection ends > v2ray.com/core/proxy/http: connection ends > v2ray.com/core/proxy/http: failed to write response > readfrom tcp 127.0.0.1:10911->127.0.0.1:62520: write tcp 127.0.0.1:10911->127.0.0.1:62520: wsasend: An established connection was aborted by the software in your host machine.
The ping of current service: -1ms
2020/08/19 06:05:28 tcp:127.0.0.1:62566 accepted tcp:settings-win.data.microsoft.com:443 [proxy] 
2020/08/19 06:06:28 tcp:127.0.0.1:62571 accepted tcp:ctldl.windowsupdate.com:80 [proxy] 
2020/08/19 06:06:28 tcp:127.0.0.1:62574 accepted tcp:ctldl.windowsupdate.com:80 [proxy] 
2020/08/19 06:06:28 tcp:127.0.0.1:62576 accepted tcp:crl.globalsign.net:80 [proxy] 
2020/08/19 06:08:58 tcp:127.0.0.1:62730 accepted tcp:34.66.232.42:80 [proxy] 



v2-ui version 
5.3.0-3

**Comment by anoircp** [comment]
thanks devs , worked now after last updates
