### ISSUE TITLE
[BUG]更改端口出现错误 必须ctrl+c结束

### ISSUE THREAD

**Issue by mlpzaq9998** [sprov065/v2-ui#355]
**你所使用的面板版本**
5.4.4

输入端口号[1-65535]: 8088
Set port to 8088 successfully

^CException ignored in: <module 'threading' from '/usr/local/v2-ui/threading.pyc'>
Traceback (most recent call last):
  File "threading.py", line 1388, in _shutdown
KeyboardInterrupt: 
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "concurrent/futures/thread.py", line 40, in _python_exit
  File "threading.py", line 1011, in join
  File "threading.py", line 1027, in _wait_for_tstate_lock
KeyboardInterrupt
设置端口完毕，现在请重启面板，并使用新设置的端口 8088 访问面板

**Comment by ZhangSir9901** [comment]
问题确认存在。

**Comment by maincooss** [comment]
问题确认存在。
情景和报错一摸一样
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"

**Comment by calonye** [comment]
同样情况
