### ISSUE TITLE
添加ssl证书报错

### ISSUE THREAD

**Issue by yuzmb** [sprov065/v2-ui#63]
日志：
asyncio-ERROR-Exception in callback BaseAsyncIOLoop._handle_events(5, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(5, 1)>
Traceback (most recent call last):
  File "asyncio/events.py", line 145, in _run
  File "tornado/platform/asyncio.py", line 138, in _handle_events
  File "tornado/netutil.py", line 273, in accept_handler
  File "tornado/tcpserver.py", line 288, in _handle_connection
  File "tornado/netutil.py", line 605, in ssl_wrap_socket
  File "tornado/netutil.py", line 574, in ssl_options_to_context
ssl.SSLError: [SSL] PEM lib (_ssl.c:3524)

证书公钥是pem格式

**Comment by sprov065** [comment]
可以尝试转换为crt格式，注意公钥和密钥文件都需要配置

**Comment by yuzmb** [comment]
我用文本也是报这个错，证书和密钥都写上了。
参考这个教程的
[](https://blog.sprov.xyz/2019/04/27/v2ray-wstls-or-http2tls-tutorial/)

难道还要配置Nginx吗

**Comment by sprov065** [comment]
那你用 nginx 反向代理吧，这个毕竟不是专门搞 ssl 的，对 ssl 的支持不一定很全面

**Comment by shoushi01** [comment]
我生成的公钥私钥都是pem格式，正常使用（v2ray和web-ui）。你看下应该有四个pem文件，你是不是把钥匙链和中间证书当做公钥上传了？

**Comment by yuzmb** [comment]
可以了，用nginx做ssl，代理转发，服务器端口不能用443和80，客户端还是用443，经过cloudflare，救活了被墙的ip，感谢作者的贡献！
